### ISSUE TITLE
Porting to RMMV (!?)

### ISSUE THREAD

**Issue by vico93** [wachunga/rmxp-multiple-message-windows#1]
Hi @wachunga !

First of all, thank you for this amazing script! Back when i used RMXP, I was amazed with it.

I came here for a question: Do you have any intention to port the system to RPG Maker MV?

I see you have knowledge of JavaScript (RMMV being a HTML5 engine using JS as script language), so i thought you would want to have a look on it.

Anyway i'm sorry if this issue just bothers you.

And again, thank for the amazing work!

**Comment by wachunga** [comment]
Thanks for the encouraging words, @vpontin. Unfortunately, I have no plans to port the script to RMMV. I've been following RMMV a little but I'm out of touch with that world. 

That said, part of my motivation for getting this script (and others) on github was to make it easier for others working on related scripts. I suspect a port wouldn't be too challenging.

If anything changes and I get involved in the RPG Maker world again, I'll be sure to let you know.

**Comment by vico93** [comment]
Thanks for the response anyway, and for keeping the script here on github!
I request in the RPG Maker forums for someone port, lets see if i have some luck!

Keep the good work!
